using System.Collections.Generic;
using System.Text.RegularExpressions;
using Terraria;
using Terraria.ID;
using Terraria.Localization;
using Terraria.ModLoader;
using JAtRT.Core.Config;
using CalamityRuTranslate.Core.Config;
using Microsoft.Xna.Framework;

public class ArmorPrefixesPrefixes : ModSystem
{
    public override bool IsLoadingEnabled(Mod mod) => (ModLoader.HasMod("ArmorAndAccessoryPrefixes") || ModLoader.HasMod("ArmorReforge")) && ModLoader.HasMod("CalamityRuTranslate") && Language.ActiveCulture.Name == "ru-RU";
    public override void PostSetupContent()
    {
        ModLoader.TryGetMod("CalamityRuTranslate", out Mod tru);

        if (TRuConfig.Instance.VanillaLocalization)
        {
            tru.Call("AddVanillaFeminineItems", new int[]
            {
                ItemID.CopperChainmail,
                ItemID.IronChainmail,
                ItemID.SilverChainmail,
                ItemID.GoldChainmail,
                ItemID.MiningHelmet,
                ItemID.CopperHelmet,
                ItemID.IronHelmet,
                ItemID.SilverHelmet,
                ItemID.GoldHelmet,
                ItemID.ShadowScalemail,
                ItemID.JungleHat,
                ItemID.JungleShirt,
                ItemID.WizardHat,
                ItemID.SummerHat,
                ItemID.PlumbersHat,
                ItemID.PlumbersShirt,
                ItemID.HerosHat,
                ItemID.HerosShirt,
                ItemID.ArchaeologistsHat,
                ItemID.ArchaeologistsJacket,
                ItemID.NinjaShirt,
                ItemID.RedHat,
                ItemID.RobotHat,
                ItemID.GoldCrown,
                ItemID.FamiliarShirt,
                ItemID.MimeMask,
                ItemID.TheDoctorsShirt,
                ItemID.CobaltHat,
                ItemID.CobaltMask,
                ItemID.MythrilHood,
                ItemID.MythrilHat,
                ItemID.MythrilChainmail,
                ItemID.AdamantiteHeadgear,
                ItemID.AdamantiteMask,
                ItemID.MiningShirt,
                ItemID.ClownHat,
                ItemID.ClownShirt,
                ItemID.HallowedMask,
                ItemID.SantaHat,
                ItemID.SantaShirt,
                ItemID.TinChainmail,
                ItemID.LeadChainmail,
                ItemID.TungstenChainmail,
                ItemID.PlatinumChainmail,
                ItemID.PlatinumCrown,
                ItemID.RuneHat,
                ItemID.RuneRobe,
                ItemID.CrimsonScalemail,
                ItemID.EskimoCoat,
                ItemID.SteampunkHat,
                ItemID.SteampunkShirt,
                ItemID.BeeHat,
                ItemID.BeeShirt,
                ItemID.PharaohsMask,
                ItemID.Tiara,
                ItemID.PharaohsRobe,
                ItemID.GreenCap,
                ItemID.MushroomCap,
                ItemID.TamOShanter,
                ItemID.MummyMask,
                ItemID.MummyShirt,
                ItemID.CowboyHat,
                ItemID.CowboyJacket,
                ItemID.PirateHat,
                ItemID.PirateShirt,
                ItemID.AncientShadowScalemail,
                ItemID.PinkEskimoCoat,
                ItemID.ChlorophyteMask,
                ItemID.RainHat,
                ItemID.TikiMask,
                ItemID.TikiShirt,
                ItemID.PalladiumMask,
                ItemID.OrichalcumMask,
                ItemID.TitaniumMask,
                ItemID.UmbrellaHat,
                ItemID.BallaHat,
                ItemID.GangstaHat,
                ItemID.SailorHat,
                ItemID.EyePatch,
                ItemID.SailorShirt,
                //Маски боссов
                ItemID.SkeletronMask,
                ItemID.BrainMask,
                ItemID.FleshMask,
                ItemID.TwinMask,
                ItemID.SkeletronPrimeMask,
                ItemID.BeeMask,
                ItemID.PlanteraMask,
                ItemID.GolemMask,
                ItemID.EaterMask,
                ItemID.EyeMask,
                ItemID.DestroyerMask,
                ItemID.KingSlimeMask,
                ItemID.DukeFishronMask,
                ItemID.BossMaskCultist,
                ItemID.BossMaskMoonlord,
                ItemID.BossMaskBetsy,
                ItemID.BossMaskDarkMage,
                ItemID.BossMaskOgre,
                ItemID.FairyQueenMask,
                ItemID.QueenSlimeMask,
                ItemID.DeerclopsMask,
                //
                ItemID.TurtleScaleMail,
                ItemID.Beanie,
                ItemID.ShroomiteMask,
                ItemID.CenxsTiara,
                ItemID.CrownosMask,
                ItemID.CenxsDressPants,
                ItemID.NurseHat,
                ItemID.WizardsHat,
                ItemID.GuyFawkesMask,
                ItemID.DyeTraderRobe,
                ItemID.CyborgShirt,
                ItemID.CreeperMask,
                ItemID.CreeperShirt,
                ItemID.CatMask,
                ItemID.CatShirt,
                ItemID.GhostMask,
                ItemID.PumpkinMask,
                ItemID.RobotHat,
                ItemID.UnicornMask,
                ItemID.VampireMask,
                ItemID.WitchHat,
                ItemID.LeprechaunHat,
                ItemID.PixieShirt,
                ItemID.BrideofFrankensteinMask,
                ItemID.KarateTortoiseMask,
                ItemID.ScarecrowHat,
                ItemID.ScarecrowShirt,
                ItemID.FoxMask,
                ItemID.SpaceCreatureMask,
                ItemID.WolfMask,
                ItemID.TreasureHunterShirt,
                ItemID.DryadCoverings,
                ItemID.DryadLoincloth,
                ItemID.JackOLanternMask,
                ItemID.MrsClauseHat,
                ItemID.MrsClauseShirt,
                ItemID.SnowHat,
                ItemID.ElfHat,
                ItemID.ElfShirt,
                ItemID.Fez,
                ItemID.SpectreMask,
                ItemID.BeetleScaleMail,
                ItemID.PeddlersHat,
                ItemID.MagicHat,
                ItemID.AnglerHat,
                ItemID.SpiderMask,
                ItemID.SeashellHairpin,
                ItemID.FishCostumeMask,
                ItemID.MoonMask,
                ItemID.SunMask,
                ItemID.MartianCostumeMask,
                ItemID.MartianUniformTorso,
                ItemID.BejeweledValkyrieHead,
                ItemID.TaxCollectorHat,
                ItemID.ClothierJacket,
                ItemID.BuccaneerBandana,
                ItemID.BuccaneerShirt,
                ItemID.ObsidianHelm,
                ItemID.TheBrideHat,
                ItemID.Yoraiz0rShirt,
                ItemID.Yoraiz0rPants,
                ItemID.SkiphsHelm,
                ItemID.EngineeringHelmet,
                ItemID.AncientBattleArmorHat,
                ItemID.LamiaHat,
                ItemID.ApprenticeHat,
                ItemID.MonkShirt,
                ItemID.MonkPants,
                ItemID.ApprenticeAltHead,
                ItemID.HuntressAltHead,
                ItemID.StarPrincessCrown,
                ItemID.StarHairpin,
                ItemID.Fedora,
                ItemID.SuperHeroMask,
                ItemID.UndertakerHat,
                ItemID.FuneralHat,
                ItemID.VictorianGothHat,
                ItemID.DrManFlyMask,
                ItemID.ButcherMask,
                ItemID.RockGolemHead,
                ItemID.MushroomHat,
                ItemID.AncientHallowedMask,
                ItemID.CrystalNinjaChestplate,
                ItemID.GraduationCapBlue,
                ItemID.GraduationCapMaroon,
                ItemID.GraduationCapBlack,
                ItemID.GraduationGownBlue,
                ItemID.GraduationGownMaroon,
                ItemID.GraduationGownBlack,
                ItemID.PlaguebringerChestplate,
                ItemID.RoninHat,
                ItemID.RoninShirt,
                ItemID.RoninPants,
                ItemID.TimelessTravelerRobe,
                ItemID.FlinxFurCoat,
                ItemID.RoyalTiara,
                ItemID.RoyalDressTop,
                ItemID.RoyalDressBottom,
                ItemID.JimsCap,
                ItemID.DizzyHat,
                ItemID.LincolnsHoodie
            });

            tru.Call("AddVanillaNeuterItems", new int[]
            {
                ItemID.EmptyBucket,
                ItemID.Robe,
                ItemID.PrincessDress,
                ItemID.AmethystRobe,
                ItemID.TopazRobe,
                ItemID.SapphireRobe,
                ItemID.EmeraldRobe,
                ItemID.DiamondRobe,
                ItemID.RubyRobe,
                ItemID.SpectreRobe,
                ItemID.CenxsDress,
                ItemID.UnicornShirt,
                ItemID.VampireShirt,
                ItemID.PrincessDressNew,
                ItemID.WitchDress,
                ItemID.BrideofFrankensteinDress,
                ItemID.KarateTortoiseShirt,
                ItemID.FoxShirt,
                ItemID.SpaceCreatureShirt,
                ItemID.WolfShirt,
                ItemID.ParkaCoat,
                ItemID.Kimono,
                ItemID.GypsyRobe,
                ItemID.MermaidAdornment,
                ItemID.FishCostumeShirt,
                ItemID.MartianCostumeShirt,
                ItemID.WhiteLunaticRobe,
                ItemID.BlueLunaticRobe,
                ItemID.TheBrideDress,
                ItemID.SkiphsShirt,
                ItemID.AncientBattleArmorShirt,
                ItemID.ApprenticeRobe,
                ItemID.ApprenticeAltShirt,
                ItemID.HuntressAltShirt,
                ItemID.MonkAltShirt,
                ItemID.MaidShirt,
                ItemID.MaidShirt2,
                ItemID.AmberRobe,
                ItemID.StarPrincessDress,
                ItemID.HeartHairpin,
                ItemID.PrettyPinkDressSkirt,
                ItemID.FuneralCoat,
                ItemID.VictorianGothDress,
                ItemID.SafemanSunDress,
                ItemID.PrinceUniform
            });

            tru.Call("AddVanillaPluralItems", new int[]
            {
                ItemID.Sunglasses,
                ItemID.Goggles,
                ItemID.CopperGreaves,
                ItemID.IronGreaves,
                ItemID.SilverGreaves,
                ItemID.GoldGreaves,
                ItemID.ShadowGreaves,
                ItemID.MeteorLeggings,
                ItemID.NecroGreaves,
                ItemID.JunglePants,
                ItemID.MoltenGreaves,
                ItemID.TuxedoPants,
                ItemID.PlumbersPants,
                ItemID.HerosPants,
                ItemID.ArchaeologistsPants,
                ItemID.NinjaPants,
                ItemID.FamiliarPants,
                ItemID.TheDoctorsPants,
                ItemID.CobaltLeggings,
                ItemID.MythrilGreaves,
                ItemID.AdamantiteLeggings,
                ItemID.MiningPants,
                ItemID.ClownPants,
                ItemID.HallowedPlateMail,
                ItemID.HallowedGreaves,
                ItemID.SantaPants,
                ItemID.RedsLeggings,
                ItemID.FrostLeggings,
                ItemID.TinGreaves,
                ItemID.LeadGreaves,
                ItemID.TungstenGreaves,
                ItemID.PlatinumGreaves,
                ItemID.WoodGreaves,
                ItemID.EbonwoodGreaves,
                ItemID.RichMahoganyGreaves,
                ItemID.PearlwoodGreaves,
                ItemID.CrimsonGreaves,
                ItemID.EskimoPants,
                ItemID.SteampunkPants,
                ItemID.BeePants,
                ItemID.MummyPants,
                ItemID.CowboyPants,
                ItemID.PiratePants,
                ItemID.CactusLeggings,
                ItemID.ShadewoodGreaves,
                ItemID.AncientShadowGreaves,
                ItemID.AncientCobaltLeggings,
                ItemID.PinkEskimoPants,
                ItemID.ChlorophytePlateMail,
                ItemID.ChlorophyteGreaves,
                ItemID.TikiPants,
                ItemID.PalladiumLeggings,
                ItemID.OrichalcumLeggings,
                ItemID.TitaniumLeggings,
                ItemID.SailorPants,
                ItemID.WhiteTuxedoPants,
                ItemID.TurtleLeggings,
                ItemID.SpectrePants,
                ItemID.ShroomiteLeggings,
                ItemID.CenxsLeggings,
                ItemID.CrownosLeggings,
                ItemID.WillsLeggings,
                ItemID.JimsLeggings,
                ItemID.AaronsLeggings,
                ItemID.DTownsLeggings,
                ItemID.PumpkinLeggings,
                ItemID.NursePants,
                ItemID.SteampunkGoggles,
                ItemID.CyborgPants,
                ItemID.CreeperPants,
                ItemID.CatPants,
                ItemID.RobotPants,
                ItemID.UnicornPants,
                ItemID.VampirePants,
                ItemID.LeprechaunPants,
                ItemID.PixiePants,
                ItemID.WitchBoots,
                ItemID.KarateTortoisePants,
                ItemID.ScarecrowPants,
                ItemID.FoxPants,
                ItemID.CatEars,
                ItemID.SpookyLeggings,
                ItemID.SpaceCreaturePants,
                ItemID.WolfPants,
                ItemID.TreasureHunterPants,
                ItemID.ReindeerAntlers,
                ItemID.MrsClauseHeels,
                ItemID.ParkaPants,
                ItemID.TreeTrunks,
                ItemID.ElfPants,
                ItemID.BeetleLeggings,
                ItemID.BeeGreaves,
                ItemID.AnglerPants,
                ItemID.SpiderGreaves,
                ItemID.BorealWoodGreaves,
                ItemID.PalmWoodGreaves,
                ItemID.VortexLeggings,
                ItemID.NebulaLeggings,
                ItemID.SolarFlareLeggings,
                ItemID.MartianCostumePants,
                ItemID.MartianUniformPants,
                ItemID.HiTekSunglasses,
                ItemID.GladiatorLeggings,
                ItemID.TaxCollectorPants,
                ItemID.ClothierPants,
                ItemID.BuccaneerPants,
                ItemID.ObsidianPants,
                ItemID.FallenTuxedoPants,
                ItemID.FossilShirt,
                ItemID.FossilPants,
                ItemID.StardustLeggings,
                ItemID.Yoraiz0rHead,
                ItemID.LokisPants,
                ItemID.FlowerBoyHat,
                ItemID.FlowerBoyShirt,
                ItemID.PedguinPants,
                ItemID.AviatorSunglasses,
                ItemID.AncientArmorPants,
                ItemID.AncientBattleArmorPants,
                ItemID.LamiaShirt,
                ItemID.ApprenticeTrousers,
                ItemID.SquirePlating,
                ItemID.SquireGreaves,
                ItemID.HuntressPants,
                ItemID.MonkBrows,
                ItemID.SquireAltPants,
                ItemID.ApprenticeAltPants,
                ItemID.HuntressAltPants,
                ItemID.MonkAltPants,
                ItemID.ArkhalisPants,
                ItemID.LeinforsPants,
                ItemID.MaidPants,
                ItemID.MaidPants2,
                ItemID.GolfPants,
                ItemID.GameMasterPants,
                ItemID.DemonHorns,
                ItemID.ChefPants,
                ItemID.BunnyEars,
                ItemID.DevilHorns,
                ItemID.SuperHeroTights,
                ItemID.PrettyPinkDressPants,
                ItemID.FuneralPants,
                ItemID.GhostarPants,
                ItemID.ButcherPants,
                ItemID.SafemanDressLeggings,
                ItemID.FoodBarbarianArmor,
                ItemID.FoodBarbarianGreaves,
                ItemID.GroxTheGreatGreaves,
                ItemID.DogEars,
                ItemID.FoxEars,
                ItemID.LizardEars,
                ItemID.PandaEars,
                ItemID.MushroomPants,
                ItemID.AncientHallowedPlateMail,
                ItemID.AncientHallowedGreaves,
                ItemID.CrystalNinjaLeggings,
                ItemID.MoonLordLegs,
                ItemID.PlaguebringerGreaves,
                ItemID.TimelessTravelerBottom,
                ItemID.FloretProtectorLegs,
                ItemID.CapricornLegs,
                ItemID.TVHeadPants,
                ItemID.PrincePants,
                ItemID.WilsonPants,
                ItemID.WillowSkirt,
                ItemID.VulkelfEar,
                ItemID.AshWoodGreaves,
                ItemID.GoblorcEar,
                ItemID.LincolnsPants
            });
        }

        if (ModLoader.TryGetMod("ModLoader", out Mod tml))
        {
            tru.Call("AddFeminineItems", tml, new[]
            {
                "Jofairden_Head",
                "AetherBreaker_Head",
                "AlejandroAkbal_Head",
                "Coolmike5000_Head",
                "dinidini_Head",
                "dschosen_Head",
                "Elfinlocks_Head",
                "Frosty_Hat",
                "Frosty_Hoodie",
                "Glory_Head",
                "Guildpack_Head",
                "HER0zero_Head",
                "Linus_Head",
                "Mayne_Head",
                "Orian_Head",
                "POCKETS_Head",
                "Polyblank_Head",
                "Remeus_Head",
                "Saethar_Head",
                "Sailing_Squid_Head",
                "Squid_Head",
                "Tantamount_Head",
                "toplayz_Head",
                "WitchDaggah_Head",
                "xAqult_Body",
                "xAqult_Head",
                "xAqult_Legs",
                "xAqult_Mask",
                "Zeph_Head"
            });

            tru.Call("AddNeuterItems", tml, new[]
            {
                "Jofairden_Body",
                "AetherBreaker_Body",
                "AlejandroAkbal_Body",
                "Coolmike5000_Body",
                "dinidini_Body",
                "dschosen_Body",
                "Elfinlocks_Body",
                "Glory_Body",
                "Guildpack_Body",
                "HER0zero_Body",
                "Linus_Body",
                "Mayne_Body",
                "Orian_Body",
                "POCKETS_Body",
                "Polyblank_Body",
                "Remeus_Body",
                "Saethar_Body",
                "Sailing_Squid_Body",
                "Squid_Body",
                "Tantamount_Body",
                "toplayz_Body",
                "Zeph_Body"
            });

            tru.Call("AddPluralItems", tml, new[]
            {
                "Jofairden_Legs",
                "AetherBreaker_Legs",
                "AlejandroAkbal_Legs",
                "Coolmike5000_Legs",
                "dinidini_Legs",
                "dschosen_Legs",
                "Elfinlocks_Legs",
                "Frosty_Pants",
                "Glory_Legs",
                "Guildpack_Legs",
                "HER0zero_Legs",
                "Linus_Legs",
                "Mayne_Legs",
                "Orian_Legs",
                "POCKETS_Legs",
                "Polyblank_Legs",
                "Remeus_Legs",
                "Saethar_Legs",
                "Sailing_Squid_Legs",
                "Squid_Legs",
                "Tantamount_Legs",
                "toplayz_Legs",
                "Zeph_Legs"
            });
        }

        if (ModLoader.TryGetMod("CalamityMod", out Mod cl) && TRuConfig.Instance.CalamityModLocalization)
        {
            tru.Call("AddFeminineItems", cl, new[]
            {
                // Маски боссов
                "AnahitaMask",
                "ApolloMask",
                "AquaticScourgeMask",
                "AresMask",
                "ArtemisMask",
                "AstrumAureusMask",
                "AstrumDeusMask",
                "BrimstoneWaifuMask",
                "BumblefuckMask",
                "CalamitasCloneMask",
                "CeaselessVoidMask",
                "CrabulonMask",
                "CryogenMask",
                "DesertScourgeMask",
                "DevouverofGodsMask",
                "DraedonMask",
                "HiveMindMask",
                "LeviathanMask",
                "OldDukeMask",
                "PerforatorMask",
                "PlaguebringerGoliathMask",
                "PolterghastMask",
                "ProfanedGuardianMask",
                "ProvidenceMask",
                "RavagerMask",
                "SignusMask",
                "SlimeGodMask",
                "SlimeGodMask2",
                "StormReaverMask",
                "ThanatosMask",
                "YharonMask",
                //
                "AerospecHat",
                "AerospecHelmet",
                "AuricTeslaHoodedFacemask",
                "AuricTeslaSpaceHelmet",
                "BloodflareHeadMelee",
                "BloodflareHeadRogue",
                "DaedalusHeadRogue",
                "DaedalusHeadSummon",
                "DesertProwlerHat",
                "DesertProwlerShirt",
                "EmpyreanMask",
                "ForbiddenCirclet",
                "GodSlayerHeadRanged",
                "GodSlayerHeadRogue",
                "HydrothermicHeadMagic",
                "HydrothermicHeadSummon",
                "MraniteArchitectToga",
                "PlagueReaperMask",
                "PrismaticRegalia",
                "ReaverScalemail",
                "SilvaHeadMagic",
                "SnowRuffianMask",
                "StatigelHeadRogue",
                "SulphurousHelmet",
                "TarragonHeadMagic",
                "TarragonHeadRogue",
                "TitanHeartMask",
                "UmbraphileRegalia",
                "OldHunterHat",
                "OldHunterShirt",
                "RobesOfCalamity",
                "SCalRobes",
                "SilvaMask",
                "VictideHeadMelee",
                "VictideHeadSummon",
                "WulfrumHat",
                "WulfrumJacket"
            });

            tru.Call("AddNeuterItems", cl, new[]
            {
                "BrimflameRobes"
            });

            tru.Call("AddPluralItems", cl, new[]
            {
                "AerospecLeggings",
                "AstralLeggings",
                "AuricTeslaCuisses",
                "BloodflareCuisses",
                "BrimflameBoots",
                "DaedalusLeggings",
                "DemonshadeGreaves",
                "DesertProwlerPants",
                "EmpyreanCuisses",
                "FathomSwarmerBoots",
                "FearmongerGreaves",
                "FearmongerPlateMail",
                "GemTechSchynbaulds",
                "GodSlayerLeggings",
                "LunicCorpsBoots",
                "MolluskShelleggings",
                "MolluskShellplate",
                "OmegaBlueTentacles",
                "PlaguebringerPistons",
                "PlagueReaperStriders",
                "PrismaticGreaves",
                "ReaverCuisses",
                "SilvaLeggings",
                "SnowRuffianGreaves",
                "StatigelGreaves",
                "SulphurousLeggings",
                "TarragonLeggings",
                "TitanHeartBoots",
                "UmbraphileBoots",
                "AncientGodSlayerLeggings",
                "AshenHorns",
                "OldHunterPants",
                "SCalBoots",
                "VictideGreaves",
                "WulfrumOverrals"
            });
        }

        if (ModLoader.TryGetMod("ThoriumMod", out Mod th) && TRuConfig.Instance.ThoriumModLocalization)
        {
            tru.Call("AddFeminineItems", th, new[]
            { 
                // Маски боссов
                "BoreanStriderMask",
                "BuriedChampionMask",
                "FallenBeholderMask",
                "ForgottenOneMask",
                "GraniteEnergyStormMask",
                "LichMask",
                "StarScouterMask",
                "QueenJellyfishMask",
                "TheGrandThunderBirdMask",
                "AquaMask",
                "OmniMask",
                "SlagMask",
                "ViscountMask",
                //
                "FlightMask",
                "CriersCap",
                "JestersMask",
                "JestersMask2",
                "JestersShirt",
                "JestersShirt2",
                "MarchingBandUniform",
                "NoblesHat",
                "OrnateHat",
                "ShootingStarHat",
                "ShootingStarShirt",
                "AncientStormMask",
                "TideTurnersGaze",
                "SoloistHat",
                "MagmaSeersMask",
                "NagaSkinMask",
                "TideHunterCap",
                "BlockyMask",
                "BlockyShirt",
                "BrutalMask",
                "CataclysmicHollowMask",
                "DannyLamentLeggings",
                "MrUniverseMask",
                "ShinobiMask",
                "SpheromacerMask",
                "WildLioncloth",
                "AbyssWalkerCuirass",
                "CasualWolfMask",
                "CasualWolfShirt",
                "DarkNexusMask",
                "DriedMask",
                "ExplosiveHat",
                "FeralFurHead",
                "FolvsAncientHat",
                "GlithcyMask",
                "GlitchyShirt",
                "GreedyHat",
                "GreedyShirt",
                "HokeMask",
                "MyrmidonCap",
                "MyrmidonTunic",
                "NightDragonMask",
                "NightDragonSkin",
                "PhantomFaceMask",
                "PhantomThiefJacket",
                "ProtogenMask",
                "PurifiersCap",
                "PurifiersUniform",
                "RedWolfMask",
                "RedWolfSuit",
                "RogueRoninHeadband",
                "StealthBandana",
                "StealthShirt",
                "SweetTunic",
                "VampireHunterBandana",
                "DragonMask",
                "SilkHat",
                "FleshMask",
                "BloomingCrown",
                "CelestialCrown",
                "FallenPaladinCuirass",
                "IridescentMail",
                "LifeBinderMask",
                "IlluminiteMask",
                "CryomancersCrown",
                "WhiteNightMask",
                "AncientHallowedChapeau",
                "AncientHallowedGuise",
                "HallowedChapeu",
                "HallowedGuise",
                "CooksHat",
                "DesertAcolyteHeadcloth",
                "DesertAcolyteTunic",
                "LifeBloomMask",
                "LivingWoodMask",
                "SpiritTrapperCuirass",
                "SpiritTrapperGreaves",
                "SpiritTrapperMask",
                "ThoriumMail",
                "FungusHat",
                "PlagueDoctorsMask",
                "ShadeMasterMask",
                "WhiteDwarfMask",
                "TitanMask",
                "MaligantCap",
                "AncientDragonMask",
                "AncientMarchingBandCap",
                "AncientMarchingBandUniform",
                "CampingCap",
                "LegendaryChainmail",
                "LightAutomatonMask",
                "LightAutomatonNuvaArmor",
                "MaroonMageHat",
                "SpaceDwarfHeadset",
                "Sunhat",
                "FishHat",
                "GelatinousMail",
                "GelatinousMask",
                "HatFish",
                "MeteorMask",
                "NoteHairpin",
                "ShadowShirt",
                "SnarbolaxCap",
                "SnarbolaxGreaves",
                "ThoriumPartyHat"
            });

            tru.Call("AddNeuterItems", th, new[]
            {
                "WildRobe",
                "DarkNexusRobe",
                "FeralFurChest",
                "FolvsAncientRobe",
                "HexingDress",
                "LunaticRobe",
                "PhantomFaceRobe",
                "ProofAvarice",
                "FleshBody",
                "CelestialVestment",
                "WarlockGarb",
                "AquamarineRobe",
                "OpalRobe",
                "ExileGarb",
                "SpiritualistRobe",
                "PlagueDoctorsGarb",
                "ShadeMasterGarb",
                "MalignatRobe",
                "CampingCoat",
                "CausticRobe",
                "MaroonMageRobe",
                "SnarbolaxCoat"
            });

            tru.Call("AddPluralItems", th, new[]
            {
                "FlightBoots",
                "FlightMail",
                "YewWoodLeggings",
                "CriersLeggings",
                "CyberPunkLeggings",
                "JestersLeggings",
                "JestersLeggings2",
                "MaestroLeggings",
                "MarchingBandLeggings",
                "NoblesLeggings",
                "OrnateLeggings",
                "ShootingStarBoots",
                "WhisperingLeggings",
                "LichTalon",
                "TideTurnerGreaves",
                "DreamWeaversTreads",
                "AssasinWalkers",
                "RhapsodistBoots",
                "PyromancerLeggings",
                "BronzeGreaves",
                "CoralGreaves",
                "DarksteelGreaves",
                "DemonBloodGreaves",
                "DepthDiverGreaves",
                "TideHunterLeggings",
                "AceGreaves",
                "BlockyPants",
                "BrutalGreaves",
                "DannyLamentLeggings",
                "GhastlyLeggings",
                "GrandThoriumGreaves",
                "HalcandranPants",
                "MrUniversePants",
                "ProspectorsShorts",
                "ShinobiTreads",
                "SpheromancerPants",
                "WildAntlers",
                "AbyssWalkerBoots",
                "BloodAstronautBoots",
                "CausalWolfPants",
                "CephalopodLeggings",
                "DarkNexusLeggings",
                "ExplosiveBooties",
                "FeralFurLegs",
                "FolvsAncientLeggings",
                "GlitchyPants",
                "GreedyPants",
                "GuardianBoots",
                "LunaticsLeggings",
                "MeatShieldsBoots",
                "MyrmidonBoots",
                "NevermoreLeggings",
                "NightDragonTalons",
                "PhantomFacePants",
                "PhantomThiefBoots",
                "ProtogenLeggings",
                "PurifiersCleats",
                "RogueRoninLeggings",
                "StealthPants",
                "SweetBoots",
                "TrashBoots",
                "UselessBoots",
                "VampireHunterBoots",
                "DragonGreaves",
                "DreadGreaves",
                "SilkLeggings",
                "FleshLegs",
                "GeodeGreaves",
                "GraniteGreaves",
                "BioTechLeggings",
                "BloomingLeggings",
                "CelestailLeggings",
                "EbonLeggings",
                "FallenPaladinGreaves",
                "IridescentGreaves",
                "LifeBinderGreaves",
                "NoviceClericPants",
                "SacredLeggings",
                "TemplarsLeggings",
                "WarlockLeggings",
                "IcyGreaves",
                "IcyMail",
                "IlluminiteGreaves",
                "LodeStoneShinGuards",
                "CryomancersLeggings",
                "WhiteKnightLeggings",
                "ConduitLeggings",
                "DesertAcolyteBoots",
                "DiverLeggings",
                "SandStoneGreaves",
                "SandStoneMail",
                "DurasteelGreaves",
                "SteelGreaves",
                "AstroBoots",
                "LifeBloomLeggings",
                "LifeBloomMail",
                "LivingWoodBoots",
                "TerrariumGreaves",
                "ThoriumGreaves",
                "FungusLeggings",
                "PlagueDoctorsLeggings",
                "ShadeMasterTreads",
                "WhiteDwarfGreaves",
                "TitanGreaves",
                "ValadiumGreaves",
                "AncientBulbLeggings",
                "AncientDragonGreaves",
                "AncientMarchingBandLeggings",
                "AncientObsidianGreaves",
                "AncientOceanGreaves",
                "AncientSandstoneGreaves",
                "AncientSandstoneMail",
                "BlueKnightGreaves",
                "BombSquadGreaves",
                "CampingCleats",
                "ChunkyGreaves",
                "ChunkyMail",
                "CausticLeggings",
                "LegendaryGreaves",
                "LightAutomatonLeggings",
                "SpaceDwarfBoots",
                "SunnySandals",
                "GelatinousGreaves",
                "GlitteringGreaves",
                "ShadowPants"
            });
        }

        if (ModLoader.TryGetMod("CatalystMod", out Mod catal) && TRuConfig.Instance.CatalystLocalization)
        {
            tru.Call("AddFeminineItems", catal, new[]
            {
                "IntergalacticHeadMagic",
                "IntergalacticHeadMelee",
                "AstrageldonMask"
            });

            tru.Call("AddPluralItems", catal, new[]
            {
                "IntergalacticGreaves"
            });
        }

        if (ModLoader.TryGetMod("CalamityHunt", out Mod calHunt) && JARTLocalizationConf.Instance.CalamityHuntFix)
        {
            tru.Call("AddFeminineItems", calHunt, new[]
            {
                "CrimulanMask",
                "DivineMask",
                "EboinianMask",
                "StellarMask"
            });

            tru.Call("AddPluralItems", calHunt, new[]
            {
                "ShogunPants"
            });
        }

        if (ModLoader.TryGetMod("Fargowiltas", out Mod fargosM) && TRuConfig.Instance.FargowiltasLocalization)
        {
            tru.Call("AddFeminineItems", fargosM, new[]
            {
                "AbominationnMask",
                "DevianttMask",
                "LumberHat",
                "LumberjackMask",
                "MutantMask"
            });

            tru.Call("AddNeuterItems", fargosM, new[]
            {
                "AbominationnBody",
                "DevianttBody",
                "LumberjackBody",
                "MutantBody"
            });

            tru.Call("AddPluralItems", fargosM, new[]
            {
                "AbominationnPants",
                "DevianttPants",
                "LumberjackPants",
                "MutantPants"
            });
        }

        if (ModLoader.TryGetMod("FargowiltasSouls", out Mod fargosS) && TRuConfig.Instance.FargowiltasSoulsLocalization)
        {
            tru.Call("AddFeminineItems", fargosS, new[]
            { 
                // Маски боссов
                "BaronMask",
                "CoffinMask",
                "DeathMask",
                "EarthMask",
                "LifeLightMask",
                "LifeMask",
                "NatureMask",
                "SpiritMask",
                "TerraMask",
                "TimberMask",
                "TrojanMask",
                "WillMask",
                //
                "EridanusHat",
                "NekomiHoodie",
                "StyxCrown"
            });

            tru.Call("AddNeuterItems", fargosS, new[]
            {
                "MutantBody",
                "MutantMask"
            });

            tru.Call("AddPluralItems", fargosS, new[]
            {
                "EridanusLegwear",
                "GaiaGreaves",
                "GaiaPlate",
                "MutantPants",
                "NekomiLeggings",
                "StyxLeggings"
            });
        }

        if (ModLoader.TryGetMod("Redemption", out Mod red) && TRuConfig.Instance.RedemptionLocalization)
        {
            tru.Call("AddFeminineItems", red, new[]
            {
                "HardlightCasque",
                "VortiHat",
                "AkkaMask",
                "AndroidHead",
                "AndroidHead2",
                "AndroidHead3",
                "TiedsMask",
                "DrillHeadHead",
                "DruidHat",
                "FowlCrown",
                "InfectedMask",
                "IntruderMask",
                "KeepersVeil",
                "KingSlayerMask",
                "NebuleusMask",
                "NebuleusMask2",
                "OOMask",
                "PZMask",
                "SkullDiggerMask",
                "AdamHead",
                "OperatorHead",
                "TBotEyes_Femi",
                "TBotEyes_Masc",
                "TBotGoggles_Femi",
                "TBotGoggles_Masc",
                "TBotVanityEyes",
                "TBotVanityGoggles",
                "VoltHead",
                "ThornMask",
                "ThornMask2",
                "UkkoMask",
                "ArchePatreonVanityHead",
                "RainPatreonVanityBody",
                "SpringtrapHead"
            });

            tru.Call("AddNeuterItems", red, new[]
            {
                "VortiRobes",
                "HallamHoodie",
                "NebuleusVanity",
                "NebuleusVanity2"
            });

            tru.Call("AddPluralItems", red, new[]
            {
                "HardlightBoots",
                "HardlightPlate",
                "XenomiteLeggings",
                "XenomitePlate",
                "HikariteGreaves",
                "ShadeLeggings",
                "ShinkiteLeggings",
                "VortiPants",
                "XeniumLeggings",
                "CommonGuardGreaves",
                "CommonGuardPlateMail",
                "DragonLeadGreaves",
                "DragonLeadRibplate",
                "ElderWoodGreaves",
                "LivingWoodLeggings",
                "PureIronGreaves",
                "HallamLeggings",
                "TiedsLeggings",
                "IntruderPants",
                "SkySquiresGreaves",
                "AndroidArmour",
                "AndroidPants",
                "JanitorPants",
                "TBotVanityLegs",
                "ArchePatreonVanityLegs",
                "MercenarysLeggings",
                "LizzyLegs",
                "MedicLegs",
                "RainPatreonVanityHead",
                "RainPatreonVanityLegs",
                "SneakloneLegs",
                "SpringtrapLegs",
                "AetherianGreaves",
                "AetherianPlatemail",
                "UnconLegs",
                "UnconLegs2"
            });
        }

        if (ModLoader.TryGetMod("HMOreSummonerHelmets", out Mod hmSumHelms) && JARTLocalizationConf.Instance.HMOreSummonerHelmetsLocalization)
        {
            tru.Call("AddFeminineItems", hmSumHelms, new[]
            {
                "OrichalcumCrown",
                "MythrilCrown"
            });

            tru.Call("AddNeuterItems", hmSumHelms, new[]
            {
                "CobaltKabuto"
            });

            tru.Call("AddPluralItems", hmSumHelms, new[]
            {
                "TitanumGrowth"
            });
        }

        if (ModLoader.TryGetMod("Clamity", out Mod clam) && JARTLocalizationConf.Instance.ClamityFix)
        {
            tru.Call("AddFeminineItems", clam, new[]
            {
                "FrozenHellstoneVisor"
            });

            tru.Call("AddPluralItems", clam, new[]
            {
                "ClamitasShelleggings",
                "ClamitasShellplate",
                "FrozenHellstoneGreaves"
            });
        }

        if (ModLoader.TryGetMod("FlinxHat", out Mod flinxHat) && JARTLocalizationConf.Instance.FlinxHatFix)
        {
            tru.Call("AddFeminineItems", flinxHat, new[]
            {
                "FlinxFurUshanka"
            });
        }

        if (ModLoader.TryGetMod("SOTS", out Mod sots))
        {
            tru.Call("AddFeminineItems", sots, new[]
            {
                "VesperaMask",
                "FlowerCrown",
                "NatureShirt",
                "FrigidCrown",
                "PatchLeatherHat",
                "PatchLeatherTunic",
                "ExcavatorMask",
                "FrigidRobe",
                "FrostArtifactMask",
                "AnubisHat",
                "PutridPinkyMask"
            });

            tru.Call("AddNeuterItems", sots, new[]
            {
                "CursedRobe"
            });

            tru.Call("AddPluralItems", sots, new[]
            {
                "ExcavatorLeggings",
                "VoidspaceLeggings",
                "ElementalLeggings",
                "VibrantLeggings",
                "VesperaLeggings",
                "NatureLeggings",
                "FrigidGreaves",
                "PatchLeatherPants",
                "EarthenLeggings",
                "DoorPants",
                "FrostArtifactTrousers",
                "TwilightAssassinsLeggings"
            });
        }

        if (ModLoader.TryGetMod("CalamityBardHealer", out Mod calBardHeal) && JARTLocalizationConf.Instance.CalamityBardHealerLocalization)
        {
            tru.Call("AddFeminineItems", calBardHeal, new[]
            {
                "BloodflareRitualistMask",
                "DaedalusHat",
                "HydrothermicHat",
                "IntergelacticCloche",
                "StatigelFoxMask",
                "TarragonChapeau",
                "TarragonParagonCrown",
                "VictideAmmoniteHat",
                "VoidFaquirChapeau"
            });

            tru.Call("AddPluralItems", calBardHeal, new[]
            {
                "AerospecHeadphones",
                "StatigelEarrings"
            });
        }

        if (ModLoader.TryGetMod("Consolaria", out Mod cons))
        {
            tru.Call("AddFeminineItems", cons, new[]
            {
                "AncientDragonMask",
                "DragonMask",
                "OstaraHat",
                "OstaraJacket",
                "OldViperChestplate",
                "AncientWarlockRobe",
                "AncientPhantasmalRobe",
                "PhantasmalRobe",
                "WarlockRobe",
                "ViperChestplate"
            });

            tru.Call("AddNeuterItems", cons, new[]
            {
                "OldSeraphimChestplate",
                "SeraphimChestplate"
            });

            tru.Call("AddPluralItems", cons, new[]
            {
                "OldViperLegs",
                "ViperLegs",
                "OldSeraphimLegs",
                "OldSirenLegs",
                "SeraphimLegs",
                "SirenLegs",
                "AncientPhantasmalSubligar",
                "AncientDragonGreaves",
                "DragonGreaves",
                "OstaraBoots",
                "AncientTitanLeggings",
                "TitanLeggings",
                "AncientWarlockLeggings",
                "WarlockLeggings"
            });
        }

        if (ModLoader.TryGetMod("MulticlassArmors", out Mod multArm) && JARTLocalizationConf.Instance.MulticlassArmorsLocalization)
        {
            tru.Call("AddFeminineItems", multArm, new[]
            {
                "ElderMagesHat"
            });

            tru.Call("AddNeuterItems", multArm, new[]
            {
                "HeatVoltConductorVest"
            });

            tru.Call("AddPluralItems", multArm, new[]
            {
                "HeatVoltConductorBoots",
                "CavernaryFlameLeggings",
                "AshensteelBoots"
            });
        }

        if (ModLoader.TryGetMod("starforgedclassic", out Mod sfc) && JARTLocalizationConf.Instance.starforgedclassicLocalization)
        {
            tru.Call("AddFeminineItems", sfc, new[]
            {
                "SunplateCrown",
                "SunplateCuirass"
            });

            tru.Call("AddPluralItems", sfc, new[]
            {
                "SunplateLeggings",
            });
        }

        if (ModLoader.TryGetMod("PathOfTerraria", out Mod pot) && TRuConfig.Instance.PathOfTerrariaLocalization)
        {
            tru.Call("AddFeminineItems", pot, new[]
            {
                "ApprenticeRobe",
                "AstralforgedAegis",
                "BatteredMail",
                "Breastplate",
                "EternalforgedAegis",
                "EtherealMantle",
                "HallowforgedCuirass",
                "IronboundCuirass",
                "ApprenticeCap",
                "Crown",
                "EtherealDiadem",
                "FirelordsWill",
                "SpectralVeil"
            });

            tru.Call("AddNeuterItems", pot, new[]
            {
                "AcolyteVestment",
                "MysticGarb",
                "PyralisHeart",
                "Visor",
                "FallenKingsLegacy"
            });

            tru.Call("AddPluralItems", pot, new[]
            {
                "BodyArmor",
                "AcolyteSandals",
                "ApprenticeSlippers",
                "AstralforgedSabatons",
                "BatteredGreaves",
                "Boots",
                "BurningRedBoots",
                "EternalforgedSabatons",
                "EtherealGreaves",
                "Greaves",
                "HallowforgedGreaves",
                "IronboundGreaves",
                "MysticBoots",
                "SpectralStriders",
                "Tassets",
                "Treads"
            });
        }
    }
}